import { DatingPlan } from '../types/plan.types';

export const INITIAL_PLANS: DatingPlan[] = [
  {
    id: 'plan_3108',
    title: 'Kế hoạch ngày 31/8',
    startDate: '2026-08-31',
    totalDays: 1,
    timeHeaderNote: '(tại cục chồng hay đi trễ)',
    summaryBudgetNote: 'Tổng chi phí (dự kiến) ~ 1 củ 🥹',
    destination: 'Sài Gòn',
    status: 'upcoming',
    transportInfo: '🛵 Cục chồng chở',
    createdBy: 'wife_id',
    createdAt: '2026-08-29T10:00:00.000Z',
    updatedAt: '2026-08-29T10:00:00.000Z',
    packingList: [
      { id: 'pack_1', name: 'Son môi & Gương mini', assignedTo: 'wife', isPacked: true },
      { id: 'pack_2', name: 'Sạc dự phòng', assignedTo: 'husband', isPacked: true },
      { id: 'pack_3', name: 'Áo khoác đôi', assignedTo: 'both', isPacked: false },
      { id: 'pack_4', name: 'Ví tiền & Căn cước', assignedTo: 'husband', isPacked: true },
    ],
    items: [
      {
        id: 'item_1',
        dayIndex: 1,
        timeRange: '09:00',
        activity: 'Xuất phát từ nhà em bé',
        emoji: '🚗',
        estimatedCost: '0đ tại có cục chồng chở',
        numericCost: 0,
        paidBy: 'husband',
        isCompleted: false,
      },
      {
        id: 'item_2',
        dayIndex: 1,
        timeRange: '10:00 - 11:00',
        activity: 'Đến YEPO - Dog & Ice Cream rùi chơi, chụp hình pla pla',
        emoji: '🐶',
        estimatedCost: '~250 - 300k',
        numericCost: 280000,
        paidBy: 'shared',
        isCompleted: false,
        notes: 'Chụp thật nhiều ảnh với cún cưng nha!',
      },
      {
        id: 'item_3',
        dayIndex: 1,
        timeRange: '11:00 - 11:15',
        activity: 'Xuất phát đi ăn Bún đậu A Chảnh',
        emoji: '🛵',
        estimatedCost: '',
        numericCost: 0,
        paidBy: 'husband',
        isCompleted: false,
      },
      {
        id: 'item_4',
        dayIndex: 1,
        timeRange: '11:15 - 12:15',
        activity: 'Nhăm nhăm bún đậu',
        emoji: '🍱',
        estimatedCost: '~200k',
        numericCost: 200000,
        paidBy: 'husband',
        isCompleted: false,
      },
      {
        id: 'item_5',
        dayIndex: 1,
        timeRange: '12:15 ~ 12:30',
        activity: 'Đi qua ún matcha',
        emoji: '🛵',
        estimatedCost: '',
        numericCost: 0,
        paidBy: 'husband',
        isCompleted: false,
      },
      {
        id: 'item_6',
        dayIndex: 1,
        timeRange: '12:30 - 13:30',
        activity: 'Japanit Matcha & Coffee House',
        emoji: '🍵',
        estimatedCost: '~200k',
        numericCost: 200000,
        paidBy: 'wife',
        isCompleted: false,
      },
      {
        id: 'item_7',
        dayIndex: 1,
        timeRange: '13:30 - 14:00',
        activity: 'Gét gô đến phần quan trọng nhất',
        emoji: '🛵',
        estimatedCost: '',
        numericCost: 0,
        paidBy: 'husband',
        isCompleted: false,
      },
      {
        id: 'item_8',
        dayIndex: 1,
        timeRange: '14:00 - 18:00',
        activity: 'Phần quan trọng nhất trong ngày',
        emoji: '❤️🔥',
        estimatedCost: '230k',
        numericCost: 230000,
        paidBy: 'husband',
        isCompleted: false,
      },
      {
        id: 'item_9',
        dayIndex: 1,
        timeRange: '18:00 - 19:00',
        activity: 'Ăn bún bò 🛵 Về nhà',
        emoji: '🍜',
        estimatedCost: '100k',
        numericCost: 100000,
        paidBy: 'husband',
        isCompleted: false,
      },
    ],
  },
  {
    id: 'plan_dalat_3n2d',
    title: 'Chuyến Đi Đà Lạt Mộng Mơ 🌸🌲',
    startDate: '2026-09-15',
    endDate: '2026-09-17',
    totalDays: 3,
    timeHeaderNote: '(Trời lạnh nhớ mặc ấm nhé em bé)',
    summaryBudgetNote: 'Tổng ngân sách dự kiến ~ 4.5 củ 💕',
    destination: 'Đà Lạt',
    status: 'upcoming',
    transportInfo: 'Xe Limousine giường đôi',
    hotelInfo: {
      name: 'Homestay Nhà Gió Rừng Thông',
      address: 'Đường Khe Sanh, Phường 10, Đà Lạt',
      checkIn: '14:00',
      checkOut: '12:00',
      cost: 1200000,
      notes: 'View thung lũng săn mây siêu đẹp',
    },
    createdBy: 'husband_id',
    createdAt: '2026-08-25T14:00:00.000Z',
    updatedAt: '2026-08-25T14:00:00.000Z',
    packingList: [
      { id: 'dl_pack_1', name: 'Áo len & Áo khoác dày', assignedTo: 'both', isPacked: true },
      { id: 'dl_pack_2', name: 'Váy hoa sống ảo 3 bộ', assignedTo: 'wife', isPacked: true },
      { id: 'dl_pack_3', name: 'Máy ảnh & Chân máy quay', assignedTo: 'husband', isPacked: false },
      { id: 'dl_pack_4', name: 'Thuốc chống say xe & Nước hoa', assignedTo: 'wife', isPacked: true },
      { id: 'dl_pack_5', name: 'Sạc dự phòng dung lượng lớn', assignedTo: 'husband', isPacked: true },
    ],
    items: [
      // Ngày 1
      {
        id: 'dl_item_1',
        dayIndex: 1,
        timeRange: '06:00 - 07:00',
        activity: 'Đến Đà Lạt, nhận xe máy & ăn Bánh mì xíu mại Ri 79',
        emoji: '🥖',
        estimatedCost: '80k',
        numericCost: 80000,
        paidBy: 'husband',
        isCompleted: false,
      },
      {
        id: 'dl_item_2',
        dayIndex: 1,
        timeRange: '08:00 - 11:30',
        activity: 'Check-in Cà phê Tiệm Túi Mơ To & Săn mây',
        emoji: '☕',
        estimatedCost: '180k',
        numericCost: 180000,
        paidBy: 'shared',
        isCompleted: false,
      },
      {
        id: 'dl_item_3',
        dayIndex: 1,
        timeRange: '12:00 - 13:30',
        activity: 'Ăn trưa Lẩu gà lá é Tao Ngộ',
        emoji: '🍲',
        estimatedCost: '300k',
        numericCost: 300000,
        paidBy: 'husband',
        isCompleted: false,
      },
      {
        id: 'dl_item_4',
        dayIndex: 1,
        timeRange: '14:00 - 17:00',
        activity: 'Về homestay nhận phòng, nghỉ ngơi & ôm nhau ngủ',
        emoji: '🏨',
        estimatedCost: '0đ',
        numericCost: 0,
        paidBy: 'shared',
        isCompleted: false,
      },
      {
        id: 'dl_item_5',
        dayIndex: 1,
        timeRange: '18:00 - 21:00',
        activity: 'Ăn nướng Bò Dã Chiến & Dạo Chợ Đêm ăn bánh tráng nướng',
        emoji: '🍢',
        estimatedCost: '450k',
        numericCost: 450000,
        paidBy: 'husband',
        isCompleted: false,
      },
      // Ngày 2
      {
        id: 'dl_item_6',
        dayIndex: 2,
        timeRange: '05:30 - 08:30',
        activity: 'Dậy sớm đón bình minh ở Đồi Cỏ Hồng & Cây thông cô đơn',
        emoji: '🌲',
        estimatedCost: '100k',
        numericCost: 100000,
        paidBy: 'husband',
        isCompleted: false,
      },
      {
        id: 'dl_item_7',
        dayIndex: 2,
        timeRange: '09:00 - 11:00',
        activity: 'Ăn Bánh ướt lòng gà Long',
        emoji: '🍜',
        estimatedCost: '120k',
        numericCost: 120000,
        paidBy: 'wife',
        isCompleted: false,
      },
      {
        id: 'dl_item_8',
        dayIndex: 2,
        timeRange: '13:00 - 16:30',
        activity: 'Đi hái dâu tây & Nông trại cún Puppy Farm',
        emoji: '🍓',
        estimatedCost: '350k',
        numericCost: 350000,
        paidBy: 'shared',
        isCompleted: false,
      },
      {
        id: 'dl_item_9',
        dayIndex: 2,
        timeRange: '18:00 - 21:30',
        activity: 'Ăn Lẩu bò Ba Toa quán gỗ & Uống sữa đậu nành nóng',
        emoji: '🥛',
        estimatedCost: '400k',
        numericCost: 400000,
        paidBy: 'husband',
        isCompleted: false,
      },
      // Ngày 3
      {
        id: 'dl_item_10',
        dayIndex: 3,
        timeRange: '08:00 - 10:00',
        activity: 'Cà phê ngắm Hồ Tuyền Lâm & Mua quà đặc sản cho gia đình',
        emoji: '🎁',
        estimatedCost: '500k',
        numericCost: 500000,
        paidBy: 'shared',
        isCompleted: false,
      },
      {
        id: 'dl_item_11',
        dayIndex: 3,
        timeRange: '11:30 - 12:30',
        activity: 'Trả phòng homestay & Lên xe về lại Sài Gòn',
        emoji: '🚌',
        estimatedCost: '0đ',
        numericCost: 0,
        paidBy: 'husband',
        isCompleted: false,
      },
    ],
  },
];
